# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FdpCoverageTool
                                 A QGIS plugin
 Optimize population coverage for distribution points.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-18
        copyright            : (C) 2025 by Sebastian Pfau
        email                : sebastian.pfau98@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

def classFactory(iface):
    """Load FdpCoverageTool class from file FdpCoverageTool.
    
    Args:
        iface: A QGIS interface instance.
    Returns:
        FdpCoverageTool: The QGIS Plugin class.
    """
    from .fdp_coverage import FdpCoverageTool
    return FdpCoverageTool(iface)
